title: Phuoc Loc Dinh
description: Machine Learning, Deep Learning, NLP, Computer Vision. 
show_downloads: false

baseurl: # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://luke-dinh.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: 

# social
author: luke-dinh
image: /thumbnail-jumbo.png
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri

header_page_refs: ['about', 'posts', 'projects' , 'contact']
